### ISSUE TITLE
Issue with my my own PAM site

### ISSUE THREAD

**Issue by millseba** [atlasbioinfo/CRISPR-CBEI#2]
I added one Cas to the table exampleBE.csv and run the code: 

autocbei -bef exampleBE.csv CDS.fasta

but I do not get the pie charts. Instead I get this message:
	CBEIPlot/CryptoDB_67_CparvumIOWA_ATCC_AnnotatedCDSs.statBar.png
No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
	CBEIPlot/CryptoDB_67_CparvumIOWA_ATCC_AnnotatedCDSs.statROC.png
	
It works perfectly fnie whe I run it by default: autocbei CDS.fasta

Best,
Sebastian

**Comment by atlasbioinfo** [comment]
Thank you for your feedback. 
I have fixed this bug a long time ago (forgot to close it), please try installing the latest version again.
All the best,
